# Please renew token. 
# Find your new token at https://cpauth.icos-cp.eu/home/ on your account information.
# Replace token every 24 hours.

auth: 
  token: cpauthToken=WzE3NjM5OTg1MTAyMDIsImMucG9wcGVAZnotanVlbGljaC5kZSIsIlNhbWwiXR4wZQIwVffvqrSGhDqgjYa38eIEWp7/Xp0wEnh4ee/p0OQ+MubUE9HXp86i5sQ5FtcVyR5LAjEAxX1JqydcQ3PCfUyKoHxP/+OKBt3H2H7WjlDuHj37d6zt5DT6byxp60MzmPm74Aju
  
station:
  id: FI-Hyy

datasets:
  #- ETC L2 Fluxnet (half-hourly)
  #- ETC NRT Meteo
  #- ETC NRT Meteosens
  - ETC L2 Meteo
  #- ETC L2 Meteosens
  #- Fluxnet Product
  #- Fluxnet Archive
  
variables:
  names:
    TA: TBOT
    RH: RH
    WS: WIND
    PA: PSRF
    P: PRECTmms
    SW_IN: FSDS
    LW_IN: FLDS
  units:
    TA: Â°C
    RH: "%"
    WS: m s-1
    PA: kPa
    P: mm
    SW_IN: W m-2
    LW_IN: W m-2
  
  